# Generated by Django 4.2.3 on 2023-08-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=100)),
                ('mstatus', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('blood', models.CharField(max_length=100)),
            ],
        ),
    ]
